#ifndef STATUS_H
	#define STATUS_H

	enum statusCode
	{
		NORMAL,
		NOT_ENOUGH_ARGUMENTS,
		DIR_DOES_NOT_EXIST,
		NO_ORDER_FILE,
		INVALID_OPTION,
		ARG_REQUIRED,
		INVALID_CHAPTER_FILE,
		CHAPTER_DOES_NOT_EXSIST,
		OUTFILE_EXISTS,
		COULD_NOT_REMOVE,
		COULD_NOT_OPEN,
		UNKOWN_ERROR,
	};

#endif
